# Generated by Django 4.1 on 2022-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('InputId', models.AutoField(primary_key=True, serialize=False)),
                ('InputDate', models.DateTimeField()),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductAmount', models.IntegerField()),
                ('Address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Outputs',
            fields=[
                ('OutputId', models.AutoField(primary_key=True, serialize=False)),
                ('OutputDate', models.DateTimeField()),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductAmount', models.IntegerField()),
                ('Address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductCode', models.CharField(max_length=500)),
                ('Manufacturer', models.CharField(max_length=500)),
                ('ProductType', models.CharField(max_length=500)),
                ('ProductDescription', models.CharField(max_length=800)),
            ],
        ),
    ]
